# Generated by Django 5.0.4 on 2024-05-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paitents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitent_ID', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Disease', models.CharField(max_length=200)),
                ('Location', models.TextField()),
            ],
        ),
    ]
